version: '3'
services:
  postgres:
    #image: agenciaimplementacion/postgres-ladm_col
    build: .
    privileged: true
    ports:
      - 5432:5432
    volumes:
      #- ./persistence:/var/lib/pgsql/9.6/data
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./scripts:/scripts:ro
      - ./sql:/sql:ro
      - .:/app:ro
