version: '3'
services:
  postgres:
    build: .
    privileged: true
    ports:
      - 5432:5432
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./scripts:/scripts/
      - .:/app
