version: '3'
services:
  postgres:
    image: agenciaimplementacion/postgres-ladm_col
    #build: .
    privileged: true
    ports:
      - 5432:5432
    volumes:
      - /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./scripts:/scripts:ro
      - ./sql:/sql:ro
      - .:/app:ro
